# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  TPTBox_config = debug_x64
endif
ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  TPTBox_config = debug_x86
endif
ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  TPTBox_config = debug_arm64
endif
ifeq ($(config),release_x64)
  raylib_config = release_x64
  TPTBox_config = release_x64
endif
ifeq ($(config),release_x86)
  raylib_config = release_x86
  TPTBox_config = release_x86
endif
ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  TPTBox_config = release_arm64
endif

PROJECTS := raylib TPTBox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C _build -f raylib.make config=$(raylib_config)
endif

TPTBox: raylib
ifneq (,$(TPTBox_config))
	@echo "==== Building TPTBox ($(TPTBox_config)) ===="
	@${MAKE} --no-print-directory -C _build -f TPTBox.make config=$(TPTBox_config)
endif

clean:
	@${MAKE} --no-print-directory -C _build -f raylib.make clean
	@${MAKE} --no-print-directory -C _build -f TPTBox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   TPTBox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"