#version 430

// Multiplication of local sizes <= 1024
layout (local_size_x = 8, local_size_y = 8, local_size_z = 16) in;

// CELL_SIZE, AIRRES, dt injected by shader loader

layout(std430, binding = 0) restrict buffer FieldIn { float fieldIn[]; };
layout(std430, binding = 1) restrict buffer FieldOu { float fieldOut[]; };

uint idx(uint x, uint y, uint z) {
    return x + y * AIRRES.x + z * AIRRES.y * AIRRES.x;
}

void main() {
    uint x = gl_GlobalInvocationID.x + 1;
    uint y = gl_GlobalInvocationID.y + 1;
    uint z = gl_GlobalInvocationID.z + 1;

    if (x >= AIRRES.x - 1 || y >= AIRRES.y - 1 || z >= AIRRES.z - 1 || x < 1 || y < 1 || z < 1)
        return;

    uint currentIdx = idx(x, y - 1, z - 1);
    float averagedVal = 0;

    // Blur kernel: e^(2 * (dx^2 + dy^2 + dz^2)) where dx,dy,dz in [-1, 1]
    averagedVal += fieldIn[currentIdx - 1] * 0.00120819;
    averagedVal += fieldIn[currentIdx + 0] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 1] * 0.00120819;
    currentIdx = idx(x, y + 0, z - 1);
    averagedVal += fieldIn[currentIdx - 1] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 0] * 0.06596478;
    averagedVal += fieldIn[currentIdx + 1] * 0.00892736;
    currentIdx = idx(x, y + 1, z - 1);
    averagedVal += fieldIn[currentIdx - 1] * 0.00120819;
    averagedVal += fieldIn[currentIdx + 0] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 1] * 0.00120819;
    currentIdx = idx(x, y - 1, z + 0);
    averagedVal += fieldIn[currentIdx - 1] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 0] * 0.06596478;
    averagedVal += fieldIn[currentIdx + 1] * 0.00892736;
    currentIdx = idx(x, y + 0, z + 0);
    averagedVal += fieldIn[currentIdx - 1] * 0.06596478;
    averagedVal += fieldIn[currentIdx + 0] * 0.48741747;
    averagedVal += fieldIn[currentIdx + 1] * 0.06596478;
    currentIdx = idx(x, y + 1, z + 0);
    averagedVal += fieldIn[currentIdx - 1] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 0] * 0.06596478;
    averagedVal += fieldIn[currentIdx + 1] * 0.00892736;
    currentIdx = idx(x, y - 1, z + 1);
    averagedVal += fieldIn[currentIdx - 1] * 0.00120819;
    averagedVal += fieldIn[currentIdx + 0] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 1] * 0.00120819;
    currentIdx = idx(x, y + 0, z + 1);
    averagedVal += fieldIn[currentIdx - 1] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 0] * 0.06596478;
    averagedVal += fieldIn[currentIdx + 1] * 0.00892736;
    currentIdx = idx(x, y + 1, z + 1);
    averagedVal += fieldIn[currentIdx - 1] * 0.00120819;
    averagedVal += fieldIn[currentIdx + 0] * 0.00892736;
    averagedVal += fieldIn[currentIdx + 1] * 0.00120819;
    fieldOut[idx(x, y, z)] = averagedVal;
}
