#version 430

// Multiplication of local sizes <= 1024
layout (local_size_x = 8, local_size_y = 8, local_size_z = 16) in;

// CELL_SIZE, AIRRES, dt, AIR_VELOCITY_LOSS injected by shader loader

layout(std430, binding = 0) restrict buffer VX { float vx[]; };
layout(std430, binding = 1) restrict buffer VY { float vy[]; };
layout(std430, binding = 2) restrict buffer VZ { float vz[]; };
layout(std430, binding = 3) readonly restrict buffer Walls { uint walls[]; };
layout(std430, binding = 4) restrict buffer Pressure { float pv[]; };

uint idx(uint x, uint y, uint z) {
    return x + y * AIRRES.x + z * AIRRES.y * AIRRES.x;
}

// Also modify in air_divergence
uint is_empty(uint x, uint y, uint z) {
    uint id = idx(x, y, z);
    return (walls[id >> 5] & (1 << (id & 31))) > 0 ? 0 : 1;
}

void main() {
    uint x = gl_GlobalInvocationID.x + 1;
    uint y = gl_GlobalInvocationID.y + 1;
    uint z = gl_GlobalInvocationID.z + 1;

    if (x >= AIRRES.x - 1 || y >= AIRRES.y - 1 || z >= AIRRES.z - 1 || x < 1 || y < 1 || z < 1)
        return;

    uint idx_here = idx(x, y, z);

    // TODO
    // if (bmap_blockair[y][x-1] || bmap_blockair[y][x] || bmap_blockair[y][x+1])
    // 	vx[y][x] = 0;
    // if (bmap_blockair[y-1][x] || bmap_blockair[y][x] || bmap_blockair[y+1][x])
    // 	vy[y][x] = 0;

    vx[idx(x, y, z)] *= AIR_VELOCITY_LOSS;
    vy[idx(x, y, z)] *= AIR_VELOCITY_LOSS;
    vz[idx(x, y, z)] *= AIR_VELOCITY_LOSS;

    // Note: vel is face centered
    float pressure_here = pv[idx_here];
    vx[idx_here] += (pv[idx_here - 1] - pressure_here) * dt * 0.5;
    vy[idx_here] += (pv[idx(x, y - 1, z)] - pressure_here) * dt * 0.5;
    vz[idx_here] += (pv[idx(x, y, z - 1)] - pressure_here) * dt * 0.5;

    // Negate velocities near walls
    // TODO
}