#version 430

// Multiplication of local sizes <= 1024
layout (local_size_x = 8, local_size_y = 8, local_size_z = 16) in;

// CELL_SIZE, AIRRES, dt injected by shader loader

layout(std430, binding = 0) readonly restrict buffer VX { float vx[]; };
layout(std430, binding = 1) readonly restrict buffer VY { float vy[]; };
layout(std430, binding = 2) readonly restrict buffer VZ { float vz[]; };

layout(std430, binding = 4) writeonly restrict buffer NVX { float new_vx[]; };
layout(std430, binding = 5) writeonly restrict buffer NVY { float new_vy[]; };
layout(std430, binding = 6) writeonly restrict buffer NVZ { float new_vz[]; };
layout(std430, binding = 7) readonly restrict buffer Walls { uint walls[]; };

layout(std430, binding = 8) readonly restrict buffer Pressure { float pv[]; };
layout(std430, binding = 9) writeonly restrict buffer NPressure { float new_pv[]; };

uint idx(uint x, uint y, uint z) {
    return x + y * AIRRES.x + z * AIRRES.y * AIRRES.x;
}

// Also modify in air_divergence
uint is_empty(uint x, uint y, uint z) {
    uint id = idx(x, y, z);
    return (walls[id >> 5] & (1 << (id & 31))) > 0 ? 0 : 1;
}

float sample_field_bilinear(vec3 pos, int field) {
    float h1 = 1.0 / float(CELL_SIZE);
    float h = float(CELL_SIZE);

    // TODO: use cursed shader macros to avoid branching
    vec3 delta = vec3(h / 2.0);
    if (field < 3)
        delta[field] = 0.0;
    pos = clamp(pos, vec3(h), vec3(h) * vec3(AIRRES.xyz));

    uvec3 MAX_COORD = uvec3(AIRRES.xyz) - uvec3(1);
    uvec3 top = uvec3((pos - delta) * h1); // top left upper corner

    // Out of bounds access
    if (clamp(top, uvec3(2), MAX_COORD - uvec3(2)) != top)
        return 0;

    uvec3 bot = min(top + uvec3(1), MAX_COORD);            // opposite corner
    vec3 t = ((pos - delta) - (vec3(top) * h)) * h1;
    vec3 s = vec3(1.0) - t;
    float c00, c01, c10, c11;

    if (field == 0) { // vx
        c00 = vx[idx(top.x, top.y, top.z)] * s.x + vx[idx(bot.x, top.y, top.z)] * t.x;
        c01 = vx[idx(top.x, top.y, bot.z)] * s.x + vx[idx(bot.x, top.y, bot.z)] * t.x;
        c10 = vx[idx(top.x, bot.y, top.z)] * s.x + vx[idx(bot.x, bot.y, top.z)] * t.x;
        c11 = vx[idx(top.x, bot.y, bot.z)] * s.x + vx[idx(bot.x, bot.y, bot.z)] * t.x;
    } else if (field == 1) { // vy
        c00 = vy[idx(top.x, top.y, top.z)] * s.x + vy[idx(bot.x, top.y, top.z)] * t.x;
        c01 = vy[idx(top.x, top.y, bot.z)] * s.x + vy[idx(bot.x, top.y, bot.z)] * t.x;
        c10 = vy[idx(top.x, bot.y, top.z)] * s.x + vy[idx(bot.x, bot.y, top.z)] * t.x;
        c11 = vy[idx(top.x, bot.y, bot.z)] * s.x + vy[idx(bot.x, bot.y, bot.z)] * t.x;
    } else if (field == 2) { // vz
        c00 = vz[idx(top.x, top.y, top.z)] * s.x + vz[idx(bot.x, top.y, top.z)] * t.x;
        c01 = vz[idx(top.x, top.y, bot.z)] * s.x + vz[idx(bot.x, top.y, bot.z)] * t.x;
        c10 = vz[idx(top.x, bot.y, top.z)] * s.x + vz[idx(bot.x, bot.y, top.z)] * t.x;
        c11 = vz[idx(top.x, bot.y, bot.z)] * s.x + vz[idx(bot.x, bot.y, bot.z)] * t.x;
    } else { // pressure
        c00 = pv[idx(top.x, top.y, top.z)] * s.x + pv[idx(bot.x, top.y, top.z)] * t.x;
        c01 = pv[idx(top.x, top.y, bot.z)] * s.x + pv[idx(bot.x, top.y, bot.z)] * t.x;
        c10 = pv[idx(top.x, bot.y, top.z)] * s.x + pv[idx(bot.x, bot.y, top.z)] * t.x;
        c11 = pv[idx(top.x, bot.y, bot.z)] * s.x + pv[idx(bot.x, bot.y, bot.z)] * t.x;
    }

    float c0 = c00 * s.y + c10 * t.y;
    float c1 = c01 * s.y + c11 * t.y;
    return c0 * s.z + c1 * t.z;
}

float sample_vx(vec3 pos) { return sample_field_bilinear(pos, 0); }
float sample_vy(vec3 pos) { return sample_field_bilinear(pos, 1); }
float sample_vz(vec3 pos) { return sample_field_bilinear(pos, 2); }
float sample_pv(vec3 pos) { return sample_field_bilinear(pos, 3); }

// vec3 curl(vec3 pos2) {
//     uvec3 pos = uvec3(pos2);
//     float dz_y = vz[idx(pos.x, pos.y + 1, pos.z)] - vz[idx(pos.x, pos.y - 1, pos.z)]; // sample_vz(pos + vec3(0, 1, 0)) - sample_vz(pos - vec3(0, 1, 0));
//     float dy_z = vy[idx(pos.x, pos.y, pos.z + 1)] - vy[idx(pos.x, pos.y, pos.z - 1)]; // sample_vy(pos + vec3(0, 0, 1)) - sample_vy(pos - vec3(0, 0, 1));
//     float dx_z = vx[idx(pos.x, pos.y, pos.z + 1)] - vx[idx(pos.x, pos.y, pos.z - 1)]; // sample_vx(pos + vec3(0, 0, 1)) - sample_vx(pos - vec3(0, 0, 1));
//     float dz_x = vz[idx(pos.x + 1, pos.y, pos.z)] - vz[idx(pos.x - 1, pos.y, pos.z)]; // sample_vz(pos + vec3(1, 0, 0)) - sample_vz(pos - vec3(1, 0, 0));
//     float dy_x = vy[idx(pos.x + 1, pos.y, pos.z)] - vy[idx(pos.x - 1, pos.y, pos.z)]; // sample_vy(pos + vec3(1, 0, 0)) - sample_vy(pos - vec3(1, 0, 0));
//     float dx_y = vx[idx(pos.x, pos.y + 1, pos.z)] - vx[idx(pos.x, pos.y - 1, pos.z)]; // sample_vx(pos + vec3(0, 1, 0)) - sample_vx(pos - vec3(0, 1, 0));
//     return vec3(
//         dz_y - dy_z,
//         dx_z - dz_x,
//         dy_x - dx_y
//     );
// }

void main() {
    uint x = gl_GlobalInvocationID.x + 1;
    uint y = gl_GlobalInvocationID.y + 1;
    uint z = gl_GlobalInvocationID.z + 1;

    if (x >= AIRRES.x - 1 || y >= AIRRES.y - 1 || z >= AIRRES.z - 1)
        return;

    uint idx_here = idx(x, y, z);
    vec3 rpos = vec3(x, y, z) * CELL_SIZE;
    vec3 vel_here;

    // Vorticity confinement
    // float Nx = length(curl(vec3(x + 1, y, z))) - length(curl(vec3(x - 1, y, z))) * 0.5;
    // float Ny = length(curl(vec3(x, y + 1, z))) - length(curl(vec3(x, y - 1, z))) * 0.5;
    // float Nz = length(curl(vec3(x, y, z + 1))) - length(curl(vec3(x, y, z - 1))) * 0.5;
    // float len = 1.0 / (sqrt(Nx * Nx + Ny * Ny + Nz * Nz) + 0.001);
    // Nx *= len;
    // Ny *= len;
    // Nz *= len;
    // vec3 curl_here = curl(vec3(x, y, z));

    float h2 = 0.5;

    // vx
    if (is_empty(x, y, z) == 1 && is_empty(x - 1, y, z) == 1 && y < AIRRES.y - 1 && z < AIRRES.z - 1) {
        vel_here = vec3(
            vx[idx_here],
            0.25 * (vy[idx_here] + vy[idx(x - 1, y, z)] + vy[idx(x, y + 1, z)] + vy[idx(x - 1, y + 1, z)]),
            0.25 * (vz[idx_here] + vz[idx(x - 1, y, z)] + vz[idx(x, y, z + 1)] + vz[idx(x - 1, y, z + 1)])
        );
        new_vx[idx_here] = clamp(sample_vx(vec3(x, y + h2, z + h2) * CELL_SIZE - dt * vel_here), -MAX_AIR_VELOCITY, MAX_AIR_VELOCITY);
            // + (Ny * curl_here.z - Nz * curl_here.y) * 0.05;
    }

    // vy
    if (is_empty(x, y, z) == 1 && is_empty(x, y - 1, z) == 1 && x < AIRRES.x - 1 && z < AIRRES.z - 1) {
        vel_here = vec3(
            0.25 * (vx[idx_here] + vx[idx(x + 1, y, z)] + vx[idx(x, y - 1, z)] + vx[idx(x + 1, y - 1, z)]),
            vy[idx_here],
            0.25 * (vz[idx_here] + vz[idx(x, y, z + 1)] + vz[idx(x, y - 1, z)] + vz[idx(x, y - 1, z + 1)])
        );
        new_vy[idx_here] = clamp(sample_vy(vec3(x + h2, y, z + h2) * CELL_SIZE - dt * vel_here), -MAX_AIR_VELOCITY, MAX_AIR_VELOCITY);
            // + (Nz * curl_here.x - Nx * curl_here.z) * 0.05;
    }

    // vz
    if (is_empty(x, y, z) == 1 && is_empty(x, y, z - 1) == 1 && y < AIRRES.y - 1 && x < AIRRES.x - 1) {
        vel_here = vec3(
            0.25 * (vx[idx_here] + vx[idx(x + 1, y, z)] + vx[idx(x, y, z - 1)] + vx[idx(x + 1, y, z - 1)]),
            0.25 * (vy[idx_here] + vy[idx(x, y + 1, z)] + vy[idx(x, y, z - 1)] + vy[idx(x, y + 1, z - 1)]),
            vz[idx_here]
        );
        new_vz[idx_here] = clamp(sample_vz(vec3(x + h2, y + h2, z) * CELL_SIZE - dt * vel_here), -MAX_AIR_VELOCITY, MAX_AIR_VELOCITY);
            // + (Nx * curl_here.y - Ny * curl_here.x) * 0.05;
    }

    // pv (note: we go against velocity if negative)

    // float pressure_multi = (pv[idx_here] < 0 ? 1 : -1);
    //  + pressure_multi * dt * vel_here * 0.5
    // sample_pv(vec3(x + h2, y + h2, z + h2) * CELL_SIZE)

    // vel_here = vec3(
    //     0.5 * (vx[idx_here] + vx[idx(x + 1, y, z)]),
    //     0.5 * (vy[idx_here] + vy[idx(x, y + 1, z)]),
    //     0.5 * (vz[idx_here] + vz[idx(x, y, z + 1)])
    // );
    // if (pv[idx_here] < 0) {
       
    //     new_pv[idx_here] = clamp(sample_pv(vec3(x + h2, y + h2, z + h2) * CELL_SIZE - dt * vel_here), -MAX_AIR_PRESSURE, MAX_AIR_PRESSURE);
    // } else
        // new_pv[idx_here] = clamp(sample_pv(vec3(x + h2, y + h2, z + h2) * CELL_SIZE + dt * vel_here), -MAX_AIR_PRESSURE, MAX_AIR_PRESSURE);
    new_pv[idx_here] = clamp(pv[idx_here], -MAX_AIR_PRESSURE, MAX_AIR_PRESSURE);

    // const uint SCALE = 2;
    // if ((z >= 40 / SCALE && z <= 40  / SCALE) && (y > 40  / SCALE && y < 50  / SCALE) && (x >= 40 / SCALE && x <= 41  / SCALE)) {
    //     new_vx[idx(x,y,z)] = 0.0;
    //     new_vy[idx(x,y,z)] = 50.0;
    //     new_vz[idx(x,y,z)] = 0.0;
    // }
    // if ((z >= 40 / SCALE  && z <= 40  / SCALE) && (y > 30 / SCALE && y < 40  / SCALE) && (x >= 40 / SCALE && x <= 41  / SCALE)) {
    //     new_vx[idx(x,y,z)] = 0.0;
    //     new_vy[idx(x,y,z)] = -50.0;
    //     new_vz[idx(x,y,z)] = 0.0;
    // }

    // Lower velocity on edges
    // if (x <= 1 || x >= AIRRES.x - 2)
    //     new_vx[idx_here] = 0.0;
    // if (y <= 1 || y >= AIRRES.y - 2)
    //     new_vy[idx_here] = 0.0;
    // if (z <= 1 || z >= AIRRES.z - 2)
    //     new_vz[idx_here] = 0.0;
}
