#version 430

// Multiplication of local sizes <= 1024
layout (local_size_x = 8, local_size_y = 8, local_size_z = 16) in;

// CELL_SIZE, AIRRES, dt injected by shader loader

layout(std430, binding = 0) restrict buffer VX { float vx[]; };
layout(std430, binding = 1) restrict buffer VY { float vy[]; };
layout(std430, binding = 2) restrict buffer VZ { float vz[]; };
layout(std430, binding = 3) restrict writeonly buffer NVX { float new_vx[]; };
layout(std430, binding = 4) restrict writeonly buffer NVY { float new_vy[]; };
layout(std430, binding = 5) restrict writeonly buffer NVZ { float new_vz[]; };
layout(std430, binding = 6) restrict readonly buffer Walls { uint walls[]; };

uniform int iteration;

// omega < 2 to guarantee convergence
const float OVER_RELAXATION = 1.97;

#import air.comp:air_idx
#import air.comp:air_is_empty

void main() {
    uint x = gl_GlobalInvocationID.x + 2;
    uint y = gl_GlobalInvocationID.y + 2;
    uint z = gl_GlobalInvocationID.z + 2;

    if (x >= AIRRES.x - 2 || y >= AIRRES.y - 2 || z >= AIRRES.z - 2)
        return;
    if (1 != is_empty(x, y, z))
        return;

    float s1 = is_empty(x - 1, y, z);
    float s2 = is_empty(x + 1, y, z);
    float s3 = is_empty(x, y - 1, z);
    float s4 = is_empty(x, y + 1, z);
    float s5 = is_empty(x, y, z - 1);
    float s6 = is_empty(x, y, z + 1);

    // Use red-black gauss-siedel
    float s = s1 + s2 + s3 + s4 + s5 + s6;
    if (s == 0) return;

    uint this_idx = idx(x, y, z);
    uint idx_x1 = this_idx + 1;
    uint idx_y1 = idx(x, y + 1, z);
    uint idx_z1 = idx(x, y, z + 1);

    float divergence =
        vx[idx_x1] - vx[this_idx] +
        vy[idx_y1] - vy[this_idx] +
        vz[idx_z1] - vz[this_idx];
    divergence /= CELL_SIZE;
    float p = -divergence / s * (OVER_RELAXATION);

    vx[this_idx] = vx[this_idx] - s1 * p;
    vx[idx_x1]   = vx[idx_x1]   + s2 * p;
    vy[this_idx] = vy[this_idx] - s3 * p;
    vy[idx_y1]   = vy[idx_y1]   + s4 * p;
    vz[this_idx] = vz[this_idx] - s5 * p;
    vz[idx_z1]   = vz[idx_z1]   + s6 * p;

    if (0 == s1) vx[this_idx] = 0.0;
    if (0 == s2) vx[idx_x1] = 0.0;
    if (0 == s3) vy[this_idx] = 0.0;
    if (0 == s4) vy[idx_y1] = 0.0;
    if (0 == s5) vz[this_idx] = 0.0;
    if (0 == s6) vz[idx_z1] = 0.0;
}
