elements = {}
table.insert(elements, "DUST")
table.insert(elements, "WATR")
table.insert(elements, "GAS")
table.insert(elements, "GOL")
table.insert(elements, "PHOT")
table.insert(elements, "GLAS")
table.insert(elements, "LAVA")
table.insert(elements, "WTRV")
--table.insert(elements, "METL")
--table.insert(elements, "PHOT")