#include "util/graphics/shader.h"
#include "rlgl.h"

#include <sstream>
#include <string>
#ifndef EMBED_SHADERS
#include "util/string.h"
#include <set>

#ifdef DEBUG
#include <regex>
#endif
#endif

util::TPBShaderSourceCode::TPBShaderSourceCode(const std::string &fname, const std::string &code)
    : m_fname(fname), m_code(code) {
#ifndef EMBED_SHADERS

    std::istringstream ss(m_code);
    std::string line, out;

#ifdef DEBUG
    std::smatch layout_match;
    std::regex layout_regex("layout\\(.*?binding\\s*=\\s*(\\d+).*?\\)");
    std::set<int> seen_bindings;
#endif
    std::map<std::string, std::set<std::string>> import_lines;

    while (std::getline(ss, line)) {
#ifdef DEBUG
        // Check for duplicate binding= definitions
        if (std::regex_search(line, layout_match, layout_regex)) {
            int binding = std::stoi(layout_match[1]);
            if (seen_bindings.contains(binding))
                throw std::runtime_error(std::format("[{}]: Duplicate binding {}", m_fname, binding));
            seen_bindings.insert(binding);
        }
#endif

        // Check for #import
        if (line.starts_with("#import ")) {
            line                    = line.substr(line.find(' ') + 1);
            auto colon              = line.find(':');
            const std::string fname = line.substr(0, colon);
            const std::string block = line.substr(colon + 1);
            import_lines[fname].insert(block);
        }
    }

    // Parse imports
    for (const auto &[fname, blocks] : import_lines) {
        std::map<std::string, std::string> block2code;
        const std::string contents = util::load_text_file("resources/shaders/imports/" + fname);

        std::istringstream ss(contents);
        std::string line, code_block = "", current_block = "";
        while (std::getline(ss, line)) {
            if (line.starts_with("#startblock ")) {
                current_block = line.substr(line.find(' ') + 1);
            } else if (!current_block.empty()) {
                if (line == "#endblock") {
                    block2code[current_block] = code_block;
                    current_block             = "";
                    code_block                = "";
                } else {
                    code_block += line;
                    code_block += '\n';
                }
            }
        }

        for (const auto &block : blocks) {
            const auto import_line = std::format("#import {}:{}", fname, block);
            size_t pos             = m_code.find(import_line);
            while (pos != std::string::npos) {
                m_code.replace(pos, import_line.size(), block2code.at(block));
                pos = m_code.find(import_line, pos + import_line.size());
            }
        }
    }
#endif
}

auto util::TPBShaderSourceCode::update() -> TPBShaderSourceCode & {
    if (m_more_lines.empty()) return *this;

    std::istringstream ss(m_code);
    std::string line, out;
    while (std::getline(ss, line)) {
        out += line;
        out += '\n';
        if (line.starts_with("#version "))
            for (const auto &extraline : m_more_lines) {
                out += extraline;
                out += '\n';
            }
    }
    m_code = out;
    return *this;
}

auto util::TPBShaderSourceCode::add_binding(unsigned int binding, const std::string &members, Restriction restrictions,
                                            const std::string_view layout) -> TPBShaderSourceCode & {
    std::string modifiers;
    switch (restrictions) {
    case NONE:      modifiers = ""; break;
    case READONLY:  modifiers = "readonly"; break;
    case WRITEONLY: modifiers = "writeonly"; break;
    }

    const std::string name = std::format("__AutoGeneratedBinding{}", binding);
    m_more_lines.push_back(std::format("layout({}, binding = {}) {} restrict buffer {} {{ {}; }};", layout, binding,
                                       modifiers, name, members));
    return *this;
}

auto util::TPBShaderSourceCode::add_const(const std::string &name, const glsl_base_t &value) -> TPBShaderSourceCode & {
    const std::string value_str = value | match{[](const auto &x) { return std::to_string(x); }};
    m_more_lines.push_back(std::format("const {} {} = {};", glsl_t_to_name(value), name, value_str));
    return *this;
}

util::TPBComputeShader::TPBComputeShader(const std::string &program) {
    unsigned int shader = rlCompileShader(program.c_str(), (int)ShaderType::COMPUTE);
    m_id                = rlLoadComputeShaderProgram(shader);
}

int util::UniformManager::get(const std::string &name) {
    auto itr = m_uniform_locs.find(name);
    if (itr != m_uniform_locs.end()) return itr->second;
    int res = GetShaderLocation(*m_shader, name.c_str());
#ifdef DEBUG
    if (res < 0)
        throw std::out_of_range(
            std::format("Uniform = '{}' does not exist for shader id= '{}'", name, m_shader->get().id));
#endif
    m_uniform_locs[name] = res;
    return res;
}
