#include "util/graphics/shader.h"
#include "rlgl.h"

#include <sstream>
#include <string>

util::TPBShaderSourceCode::TPBShaderSourceCode(const std::string &code) : m_code(code) {}

auto util::TPBShaderSourceCode::update() -> TPBShaderSourceCode & {
    if (m_more_lines.empty()) return *this;

    std::istringstream ss(m_code);
    std::string line, out;
    while (std::getline(ss, line)) {
        out += line;
        out += '\n';
        if (line.starts_with("#version "))
            for (const auto &extraline : m_more_lines) {
                out += extraline;
                out += '\n';
            }
    }
    m_code = out;
    return *this;
}

auto util::TPBShaderSourceCode::add_binding(unsigned int binding, const std::string &members, Restriction restrictions,
                                        const std::string_view layout) -> TPBShaderSourceCode & {
    std::string modifiers;
    switch (restrictions) {
    case NONE:      modifiers = ""; break;
    case READONLY:  modifiers = "readonly"; break;
    case WRITEONLY: modifiers = "writeonly"; break;
    }

    const std::string name = std::format("__AutoGeneratedBinding{}", binding);
    m_more_lines.push_back(std::format("layout({}, binding = {}) {} restrict buffer {} {{ {}; }};", layout, binding,
                                       modifiers, name, members));
    return *this;
}

auto util::TPBShaderSourceCode::add_const(const std::string &name, const glsl_base_t &value) -> TPBShaderSourceCode & {
    const std::string value_str = value | match{[](const auto &x) { return std::to_string(x); }};
    m_more_lines.push_back(std::format("const {} {} = {};", glsl_t_to_name(value), name, value_str));
    return *this;
}

util::TPBComputeShader::TPBComputeShader(const std::string &program) {
    unsigned int shader = rlCompileShader(program.c_str(), (int)ShaderType::COMPUTE);
    m_id                = rlLoadComputeShaderProgram(shader);
}

int util::UniformManager::get(const std::string &name) {
    auto itr = m_uniform_locs.find(name);
    if (itr != m_uniform_locs.end())
        return itr->second;
    int res = GetShaderLocation(*m_shader, name.c_str());
    #ifdef DEBUG
    if (res < 0)
        throw std::out_of_range(std::format("Uniform = '{}' does not exist for shader id= '{}'", name, m_shader->get().id));
    #endif
    m_uniform_locs[name] = res;
    return res;
}
